linux_release:
  image: greenaddress/wallycore@sha256:48a02e07aa1264a549413c2c2f765d183c53d660b450db245d2444751622cd21
  artifacts:
    expire_in: 14 days
    name: wallycore-bindings
    when: on_success
    paths:
    - wallycore-android-jni.tar.gz
    - wallycore-android-jni.tar.gz.sha256
    - wallycore-0.4.0-cp27-cp27mu-linux_x86_64.whl
    - wallycore-0.4.0-cp27-cp27mu-linux_x86_64.whl.sha256
    - wallycore-0.4.0-cp35-cp35m-linux_x86_64.whl
    - wallycore-0.4.0-cp35-cp35m-linux_x86_64.whl.sha256
    - wallycore-linux_x86_64-python2.tar.gz
    - wallycore-linux_x86_64-python2.tar.gz.sha256
    - wallycore-linux_x86_64-python3.tar.gz
    - wallycore-linux_x86_64-python3.tar.gz.sha256
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build_python_eggs.sh
    - ./tools/build_android_libraries.sh
    - mv release wallycore-android-jni
    - tar cvf wallycore-android-jni.tar wallycore-android-jni
    - gzip -9 wallycore-android-jni.tar
    - shasum -a 256 wallycore-android-jni.tar.gz > wallycore-android-jni.tar.gz.sha256

osx_release:
  tags:
    - osx
  artifacts:
    expire_in: 14 days
    name: wallycore-bindings
    when: on_success
    paths:
    - wallycore-0.4.0-cp27-cp27m-macosx_10_12_x86_64.whl
    - wallycore-0.4.0-cp27-cp27m-macosx_10_12_x86_64.whl.sha256
    - wallycore-0.4.0-cp36-cp36m-macosx_10_12_x86_64.whl
    - wallycore-0.4.0-cp36-cp36m-macosx_10_12_x86_64.whl.sha256
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build_python_eggs.sh

armv7l_release:
  tags:
    - armv7l
  artifacts:
    expire_in: 14 days
    name: wallycore-bindings
    when: on_success
    paths:
    - wallycore-0.4.0-*.whl
    - wallycore-0.4.0-*.whl.sha256
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build_python_eggs.sh

arm64_release:
  tags:
    - arm64
  artifacts:
    expire_in: 14 days
    name: wallycore-bindings
    when: on_success
    paths:
    - wallycore-0.4.0-*.whl
    - wallycore-0.4.0-*.whl.sha256
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build_python_eggs.sh

mips_release:
  tags:
    - mips
  script:
    - ./tools/build_python_eggs.sh

freebsdamd64_release:
  tags:
    - freebsd
  artifacts:
    expire_in: 14 days
    name: wallycore-bindings
    when: on_success
    paths:
    - wallycore-0.4.0-*.whl
    - wallycore-0.4.0-*.whl.sha256
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build_python_eggs.sh

windows10_release:
  tags:
    - win10
  artifacts:
    name: wallycore-dll
    when: on_success
    paths:
    - wally.dll
    - wally.lib
  script:
    - cd %CI_PROJECT_DIR%
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
    - tools\msvc\build.bat
