git:
    depth: 5
branches:
    only:
      - master
      - travis_testing
addons:
    apt:
        packages:
          - python
          - python-dev
          - python3
          - python3-dev
          - swig
          - gcc-multilib

matrix:
  include:
    - compiler: clang
      env: HOST=i686-linux-gnu
    - compiler: gcc
      env: HOST=i686-linux-gnu

language: c
sudo: false
compiler:
  - clang
  - gcc
before_script:
  - ./cleanup.sh && ./autogen.sh
script:
  - export USE_SWIG_PYTHON="--enable-swig-python"
  - if [ -n "$HOST" ]; then
        export USE_HOST="--host=$HOST"
        if [ "$HOST" = "i686-linux-gnu" ]; then
            export CC="$CC -m32"
            export USE_SWIG_PYTHON=""
        fi
    fi
  - ./configure --enable-silent-rules --enable-export-all $USE_SWIG_PYTHON --enable-swig-java $USE_HOST && make && make check
os: linux
