git:
    depth: 5
branches:
    only:
      - travis
addons:
    apt:
        packages:
          - python
          - python-dev
          - python3
          - python3-dev
          - swig

language: c
sudo: false
compiler:
  - clang
  - gcc
before_script:
  - ./cleanup.sh && ./autogen.sh
script:
  - ./configure --enable-export-all --enable-swig-python --enable-swig-java && make check
os: linux
