git:
    depth: 5
branches:
    only:
      - master
      - travis_testing
addons:
    apt:
        packages:
          - python
          - python-dev
          - python3
          - python3-dev
          - swig
          - gcc-multilib

matrix:
  include:
    - compiler: clang
      env: HOST=i686-linux-gnu
    - compiler: gcc
      env: HOST=i686-linux-gnu

language: c
sudo: false
compiler:
  - clang
  - gcc
before_script:
  - ./tools/cleanup.sh && ./tools/autogen.sh
script:
  - ./tools/travis_build.sh
os: linux
