git:
    depth: 5
branches:
    only:
      - master
      - travis_testing
addons:
    apt:
        packages:
          - python
          - python-dev
          - python3
          - python3-dev
          - swig
          - gcc-multilib

matrix:
  include:
    - compiler: clang
      env: HOST=i686-linux-gnu
    - compiler: gcc
      env: HOST=i686-linux-gnu

language: c
sudo: false
compiler:
  - clang
  - gcc
before_script:
  - ./cleanup.sh && ./autogen.sh
script:
  - if [ -n "$HOST" ]; then export USE_HOST="--host=$HOST"; fi
  - if [ "x$HOST" = "xi686-linux-gnu" ]; then export CC="$CC -m32"; fi
  - ./configure --enable-silent-rules --enable-export-all --enable-swig-python --enable-swig-java $USE_HOST && make && make check
os: linux
